apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-service
  labels:
    app: webhook-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-service
  template:
    metadata:
      labels:
        app: webhook-service
    spec:
      containers:
      - name: webhook-service
        image: claude-webhook-service:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: PORT
          value: "5000"
        - name: DEBUG
          value: "false"
        - name: JIRA_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: webhook-config
              key: jira-base-url
        volumeMounts:
        - name: routing-config
          mountPath: /config
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: routing-config
        configMap:
          name: webhook-routing-config