apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
  labels:
    app: nginx-proxy
    component: reverse-proxy
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-proxy

---
# Internal ClusterIP service for cluster communication
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-internal
  labels:
    app: nginx-proxy
    component: reverse-proxy
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-proxy

---
# NodePort service for environments without LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-nodeport
  labels:
    app: nginx-proxy
    component: reverse-proxy
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    nodePort: 30443
    protocol: TCP
    name: https
  selector:
    app: nginx-proxy