apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claude-dev-workspace
  labels:
    app: claude-dev-env
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # Uncomment and modify if you have a specific storage class
  # storageClassName: your-storage-class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claude-dev-config
  labels:
    app: claude-dev-env
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # Uncomment and modify if you have a specific storage class
  # storageClassName: your-storage-class